{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "metabase-app.fullname" . }}*/}}
{{/*  labels:*/}}
{{/*    app.kubernetes.io/name: {{ include "metabase-app.name" . }}*/}}
{{/*    helm.sh/chart: {{ include "metabase-app.chart" . }}*/}}
{{/*    app.kubernetes.io/instance: {{ .Release.Name }}*/}}
{{/*    app.kubernetes.io/managed-by: {{ .Release.Service }}*/}}
{{/*spec:*/}}
{{/*  replicas: {{ .Values.replicaCount }}*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app.kubernetes.io/name: {{ include "metabase-app.name" . }}*/}}
{{/*      app.kubernetes.io/instance: {{ .Release.Name }}*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app.kubernetes.io/name: {{ include "metabase-app.name" . }}*/}}
{{/*        app.kubernetes.io/instance: {{ .Release.Name }}*/}}
{{/*    spec:*/}}
{{/*      containers:*/}}
{{/*        - name: metabase*/}}
{{/*          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"*/}}
{{/*          imagePullPolicy: {{ .Values.image.pullPolicy }}*/}}
{{/*          ports:*/}}
{{/*            - name: http*/}}
{{/*              containerPort: 3000*/}}
{{/*              protocol: TCP*/}}
{{/*          env:*/}}
{{/*            - name: MB_DB_PASS*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: {{.Values.secrets.mb_db_pass_id}}*/}}
{{/*                  key: MB_DB_PASS*/}}
{{/*          envFrom:*/}}
{{/*            - configMapRef:*/}}
{{/*                name: metebase-config*/}}
{{/*          resources:*/}}
{{/*            {{- toYaml .Values.resources | nindent 12 }}*/}}