apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "metabase-app.fullname" . }}-db
type: Opaque
data:
{{/*  MB_DB_PASS: "Y2hhbmdlTWUxMjMh"*/}}
  MB_DB_PASS: {{.Values.env.MB_DB_PASS }}
{{/*  MB_DB_PASS: {{.Values.env.MB_DB_PASS | b64enc}}*/}}
