ingress:
  host: metabase.yourdomain.com
image:
  repository: metabase/metabase
  tag: v0.49.3
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 80

env:
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: "5432"
  MB_DB_USER: metabase_user
  MB_DB_PASS: ""     # will be overridden by secret
  MB_DB_HOST: ""     # will be overridden by secret

resources:
  limits:
    cpu: 1
    memory: 2024Mi
  requests:
    cpu: 1
    memory: 1024Mi
