image:
  repository: metabase/metabase
  tag: v0.49.3
  pullPolicy: IfNotPresent

secrets:
  mb_db_pass_id: metabase-app-db

replicaCount: 1

service:
  type: LoadBalancer
  port: 80

env:
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: "5432"
  MB_DB_USER: metabaseuser
  MB_DB_HOST: "metabase-postgres.c7df0wwhxfnn.us-east-1.rds.amazonaws.com"     # will be overridden by secret

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 1
    memory: 1024Mi